name: Bump Test Scripts Version
on:
  push:
    branches:
      - main1
  pull_request:
    types:
      - labeled

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haya14busa/action-bumpr@v1
